[package]
name = "twitchchat"
version = "0.7.2"
authors = ["museun <museun@outlook.com>"]
repository = "https://github.com/museun/twitchchat"
edition = "2018"
readme = "README.md"
description = "interface to the irc-side of twitch's chat system"
keywords = [ "twitch", "irc" ]
license = "0BSD"

[badges]
circle-ci = { repository = "museun/twitchchat", branch = "master", service = "github" }
maintenance = { status = "actively-developed" }

[dependencies]
log = "0.4.8"
crossbeam-channel = "0.3.9"
rate_limit = "0.1.1"

[dependencies.serde]
version = "1.0.101"
features = ["derive"]
optional = true

[features]
default = []
serde_derive = [ "serde" ]

[dev-dependencies]
rand = "0.7.2"
serde_json = "1.0.41"
