[package]
name = "twitchchat"
version = "0.4.3"
authors = ["museun <museun@outlook.com>"]
repository = "https://github.com/museun/twitchchat"
edition = "2018"
readme = "README.md"
description = "interface to the irc-side of twitch's chat system"
keywords = [ "twitch", "irc" ]
license = "0BSD"

[badges]
circle-ci = { repository = "museun/twitchchat", branch = "master", service = "github" }
maintenance = { status = "actively-developed" }

[dependencies]
log = "0.4.6"

[dependencies.parking_lot]
version = "0.7.1"
optional = true

[dependencies.hashbrown]
version = "0.2.0"
optional = true

[dependencies.serde]
version = "1.0.90"
features = ["derive"]
optional = true

[features]
default = [ "all" ]
serde_hashbrown = ["serde", "hashbrown/serde"]
all = ["serde_hashbrown", "parking_lot"]

[dev-dependencies]
rand = "0.6.5"
serde_json = "1.0.39"
