[package]
name = "twitchchat"
version = "0.1.11"
authors = ["museun <museun@outlook.com>"]
repository = "https://github.com/museun/twitchchat"
edition = "2018"
description = "interface to the irc-side of twitch's chat system"
keywords = [ "twitch", "irc" ]
license = "0BSD"

[badges]
circle-ci = { repository = "https://github.com/museun/twitchchat", branch = "master" }
maintenance = { status = "actively-developed" }

[dependencies]
log = "0.4.6"

[dependencies.parking_lot]
version = "0.7.1"
optional = true

[dependencies.hashbrown]
version = "0.1.8"
optional = true

[dependencies.serde]
version = "1.0.89"
features = ["derive"]
optional = true

[features]
default = []
serde_hashbrown = ["serde", "hashbrown/serde"]
all = ["serde_hashbrown", "parking_lot"]
