[target.aarch64-linux-android]
image = "chronophylos/cross:aarch64-linux-android"

[target.arm-unknown-linux-gnueabi]
image = "chronophylos/cross:arm-unknown-linux-gnueabi"

[target.armv5te-unknown-linux-gnueabi]
image = "chronophylos/cross:armv5te-unknown-linux-gnueabi"

[target.armv7-linux-androideabi]
image = "chronophylos/cross:armv7-linux-androideabi"

[target.armv7-unknown-linux-gnueabihf]
image = "chronophylos/cross:armv7-unknown-linux-gnueabihf"

[target.i686-linux-android]
image = "chronophylos/cross:i686-linux-android"

[target.i686-unknown-linux-gnu]
image = "chronophylos/cross:i686-unknown-linux-gnu"

[target.powerpc64-unknown-linux-gnu]
image = "chronophylos/cross:powerpc64-unknown-linux-gnu"

[target.powerpc64le-unknown-linux-gnu]
image = "chronophylos/cross:powerpc64le-unknown-linux-gnu"

[target.riscv64gc-unknown-linux-gnu]
image = "chronophylos/cross:riscv64gc-unknown-linux-gnu"

[target.s390x-unknown-linux-gnu]
image = "chronophylos/cross:s390x-unknown-linux-gnu"

[target.wasm32-unknown-emscripten]
image = "chronophylos/cross:wasm32-unknown-emscripten"

[target.x86_64-linux-android]
image = "chronophylos/cross:x86_64-linux-android"

[target.x86_64-pc-windows-gnu]
image = "chronophylos/cross:x86_64-pc-windows-gnu"

[target.x86_64-unknown-linux-gnu]
image = "chronophylos/cross:x86_64-unknown-linux-gnu"

