name: Rust

on: [push]

jobs:
  build:
    strategy:
      matrix:
        target:
          - aarch64-apple-ios
          - aarch64-linux-android
          - aarch64-pc-windows-msvc
          - arm-unknown-linux-gnueabi
          - armv7-linux-androideabi
          - armv7-unknown-linux-gnueabihf
          - i686-linux-android
          - i686-pc-windows-msvc
          - i686-unknown-linux-gnu
          - mips-unknown-linux-gnu
          - powerpc-unknown-linux-gnu
          - powerpc64-unknown-linux-gnu
          - powerpc64le-unknown-linux-gnu
          - riscv64gc-unknown-linux-gnu
          - s390x-unknown-linux-gnu
          - wasm32-unknown-emscripten
          - x86_64-apple-darwin
          - x86_64-linux-android
          - x86_64-pc-windows-gnu
          - x86_64-pc-windows-msvc
          - x86_64-unknown-freebsd
          - x86_64-unknown-linux-gnu
          - x86_64-unknown-linux-gnu
          - aarch64-apple-ios
        rust:
          - stable
          - nightly
          - beta
        os:
          - ubuntu-latest
        include:
          - target: aarch64-apple-ios
            os: macos-latest
          - target: x86_64-apple-ios
            os: macos-latest
        exclude:
          - target: aarch64-apple-ios
            os: ubuntu-latest
          - target: x86_64-apple-ios
            os: ubuntu-latest

    runs-on: ${{matrix.os}}

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{matrix.rust}}
          target: ${{matrix.target}}
          override: true

      - name: Build default features
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --target ${{matrix.target}}

      - name: Run tests default features
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: test
          args: --target ${{matrix.target}}

      - name: Build all features
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --target ${{matrix.target}} --all-features

      - name: Run tests all features
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: test
          args: --target ${{matrix.target}} --all-features

      - name: Build no features
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --target ${{matrix.target}} --no-default-features

      - name: Run tests with no features
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: test
          args: --target ${{matrix.target}} --no-default-features

      - name: Build only async
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --target ${{matrix.target}} --no-default-features --features async

      - name: Run tests only async
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: test
          args: --target ${{matrix.target}} --no-default-features --features async

      - name: Build rustls
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --target ${{matrix.target}} --no-default-features --features tokio_rustls

      - name: Run tests rustls
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: test
          args: --target ${{matrix.target}} --no-default-features --features tokio_rustls

      - name: Build native_tls
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --target ${{matrix.target}} --no-default-features --features tokio_native_tls

      - name: Run tests native_ts
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: test
          args: --target ${{matrix.target}} --no-default-features --features tokio_native_tls
